import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
const root=process.cwd();
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const sequence=read('.github/workflows/ai-advisory-review-sequence.yml');
const runner=read('.github/workflows/ai-advisory-review-runner.yml');
const manual=read('.github/workflows/additional-ai-advisory-reviews.yml');
const policy=read('POLICY.md');
const wiring=read('docs/SKILL_WIRING.md');
const skill=read('skills/governance/ai-advisory-review/SKILL.md');
const next=read('Masterplan/NEXT_SLICES.md');
const session=read('AI_ASSISTANT_READ_ME.md');
const aliases=['OPENROUTER_API_KEY','OPENROUTER_API_KEY_OPENAI','OPENROUTER_API_KEY_POOLSIDE','OPENROUTER_API_KEY_DEEPSEEK','OPENROUTER_API_KEY_GWEN'];
test('automatic fan-out uses five dedicated credential aliases',()=>{for(const alias of aliases) assert.match(sequence,new RegExp('credential_alias:\\s*'+alias));assert.match(sequence,/secrets\[matrix\.credential_alias\]/);assert.doesNotMatch(sequence,/model:\s*openrouter\/free/);assert.doesNotMatch(sequence,/secrets\.OPENROUTER_API_KEY \}\}/);assert.doesNotMatch(sequence,/issues\/\$PR\/comments/);});
test('runner hard-locks route without model-specific approval inputs',()=>{assert.match(runner,/MODEL:\s*openrouter\/free/);assert.doesNotMatch(runner,/^\s+model:\s*$/m);assert.doesNotMatch(runner,/approve:/i);assert.match(runner,/actions\/upload-artifact@v4/);assert.doesNotMatch(runner,/automatic_outcome_marker/);});
test('manual slots map to distinct aliases',()=>{for(const alias of aliases) assert.match(manual,new RegExp('credential_alias:\\s*'+alias));});
test('active governance surfaces teach no retired advisory topology',()=>{for(const text of [sequence,runner,manual,policy,wiring,skill,next,session]) for(const token of ['1→2→2','150-second','one shared OpenRouter API key','comment-driven orchestration state','skills/governance/nemotron-copilot-review']) assert.doesNotMatch(text,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'));});
test('retired files are archived, not active',()=>{assert.equal(fs.existsSync(path.join(root,'docs/TEAMAI_029_CURRENT_STATE_MAP.md')),false);assert.equal(fs.existsSync(path.join(root,'.github/workflows/nemotron-copilot-review.yml')),false);assert.equal(fs.existsSync(path.join(root,'skills/governance/nemotron-copilot-review/SKILL.md')),false);assert.equal(fs.existsSync(path.join(root,'docs/archive/TEAMAI_029_CURRENT_STATE_MAP_legacy_2026-09-19.md')),true);});
test('session snapshot and current slice are explicit',()=>{assert.match(session,/## SESSION SNAPSHOT/);assert.match(session,/replacement branch: rebuild\/clean-mainline-20260919/);assert.match(session,/open implementation vehicles: #389 only/);assert.match(next,/GOVERNANCE — clean canonical mainline reconstruction \(Issue #389\)/);});