import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
const root=process.cwd();
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const sequence=read('.github/workflows/ai-advisory-review-sequence.yml');
const runner=read('.github/workflows/ai-advisory-review-runner.yml');
const manual=read('.github/workflows/additional-ai-advisory-reviews.yml');
const policy=read('POLICY.md');
const wiring=read('docs/SKILL_WIRING.md');
const skill=read('skills/governance/ai-advisory-review/SKILL.md');
const next=read('Masterplan/NEXT_SLICES.md');
const session=read('AI_ASSISTANT_READ_ME.md');
const aliases=['OPENROUTER_API_KEY','OPENROUTER_API_KEY_OPENAI','OPENROUTER_API_KEY_POOLSIDE','OPENROUTER_API_KEY_DEEPSEEK','OPENROUTER_API_KEY_GWEN'];
test('automatic fan-out uses five dedicated credential aliases',()=>{for(const alias of aliases) assert.match(sequence,new RegExp('credential_alias:\\s*'+alias));assert.match(sequence,/secrets\[matrix\.credential_alias\]/);assert.doesNotMatch(sequence,/model:\s*openrouter\/free/);assert.doesNotMatch(sequence,/secrets\.OPENROUTER_API_KEY \}\}/);assert.doesNotMatch(sequence,/issues\/\$PR\/comments\?per_page/);});
test('terminal slot outcomes do not fail sequence orchestration',()=>{const block=sequence.slice(sequence.indexOf('  openrouter_free:'),sequence.indexOf('  sequence_complete:'));assert.match(block,/continue-on-error:\s*true/);assert.match(sequence,/structured slot artifacts/);});
test('runner hard-locks route and uses structured advisory output',()=>{assert.match(runner,/MODEL:\s*openrouter\/free/);assert.doesNotMatch(runner,/^\s+model:\s*$/m);assert.doesNotMatch(runner,/approve:/i);assert.match(runner,/response_format/);assert.match(runner,/'type': 'json_schema'/);assert.match(runner,/teamai_advisory_review/);assert.match(runner,/failure_path\.exists\(\)/);assert.match(runner,/actions\/upload-artifact@v4/);assert.doesNotMatch(runner,/automatic_outcome_marker/);});
test('provider capability controls remain enforced',()=>{assert.match(runner,/require_parameters/);assert.match(runner,/response-healing/);assert.match(runner,/stream.*False/);});
test('automatic sequence evidence publisher is authenticated',()=>{assert.match(sequence,/Build and publish execution evidence[\s\S]{0,500}GH_TOKEN: \$\{\{ github\.token \}\}/);assert.match(sequence,/gh api --method POST/);});
test('validation workflows avoid duplicate PR branch pushes',()=>{const full=fs.readFileSync(path.join(root,'.github/workflows/full-system-verification.yml'),'utf8');const browser=fs.readFileSync(path.join(root,'.github/workflows/playwright.yml'),'utf8');assert.match(full,/push:\n\s+branches: \[main\]/);assert.match(browser,/push:\n\s+branches: \[main\]/);assert.doesNotMatch(full,/governance\/repository-foundation/);assert.doesNotMatch(browser,/governance\/repository-foundation/);});
test('manual and Skill Wiring routes map to distinct aliases',()=>{for(const alias of aliases){assert.ok(manual.includes(alias));assert.ok(wiring.includes('| '+alias+' |'));}});
for(const text of [sequence,runner,manual,policy,wiring,skill,next]) for(const token of ['1→2→2','150-second','one shared OpenRouter API key','comment-driven orchestration state','skills/governance/nemotron-copilot-review']) { const escaped = token.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); assert.doesNotMatch(text,new RegExp(escaped,'i')); }
test('retired files are archived, not active',()=>{assert.equal(fs.existsSync(path.join(root,'docs/TEAMAI_029_CURRENT_STATE_MAP.md')),false);assert.equal(fs.existsSync(path.join(root,'.github/workflows/nemotron-copilot-review.yml')),false);assert.equal(fs.existsSync(path.join(root,'skills/governance/nemotron-copilot-review/SKILL.md')),false);assert.equal(fs.existsSync(path.join(root,'docs/archive/TEAMAI_029_CURRENT_STATE_MAP_legacy_2026-09-19.md')),true);});
test('session snapshot and current slice are explicit',()=>{assert.match(session,/## SESSION SNAPSHOT/);assert.match(session,/replacement branch: governance\/clean-mainline-rebuild-20260919/);assert.match(session,/open implementation vehicles: PR #391 \/ Issue #389 only/);assert.match(next,/GOVERNANCE — clean canonical mainline reconstruction \(Issue #389\)/);});