import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
const root=process.cwd();
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const sequence=read('.github/workflows/ai-advisory-review-sequence.yml');
const runner=read('.github/workflows/ai-advisory-review-runner.yml');
const governance=read('.github/workflows/governance.yml');
const manual=read('.github/workflows/additional-ai-advisory-reviews.yml');
const controlPlaneValidator=read('scripts/governance/verify-advisory-control-plane.mjs');
const policy=read('POLICY.md');
const wiring=read('docs/SKILL_WIRING.md');
const skill=read('skills/governance/ai-advisory-review/SKILL.md');
const next=read('Masterplan/NEXT_SLICES.md');
const session=read('AI_ASSISTANT_READ_ME.md');
const manifest=JSON.parse(read('.github/teamai/authority-manifest.yml'));
const slots=manifest.advisory_review.slots;
const aliases=slots.map(slot=>slot.credential_alias);
const escapeRegExp=value=>value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
test('automatic fan-out consumes the canonical advisory registry',()=>{assert.equal(manifest.advisory_review.route,'openrouter/free');assert.deepEqual(slots.map(s=>s.slot),[1,2,3,4,5]);assert.deepEqual(slots.map(s=>s.start_delay_seconds),[0,2,4,6,8]);assert.match(sequence,/resolve_advisory_slots/);assert.match(sequence,/fromJSON\(needs\.resolve_advisory_slots\.outputs\.matrix\)/);assert.match(sequence,/credential_alias: \$\{\{ matrix\.credential_alias \}\}/);assert.match(sequence,/secrets\[matrix\.credential_alias\]/);assert.match(sequence,/cancel-in-progress:\s*false/);for(const alias of aliases){const escaped=escapeRegExp(alias);assert.doesNotMatch(sequence,new RegExp(escaped));assert.doesNotMatch(manual,new RegExp(escaped));assert.doesNotMatch(runner,new RegExp(escaped));}});
test('terminal slot outcomes are aggregated without reusable-job continue-on-error',()=>{const block=sequence.slice(sequence.indexOf('  openrouter_free:'),sequence.indexOf('  sequence_complete:'));assert.doesNotMatch(block,/continue-on-error:\s*true/);assert.match(sequence,/sequence_complete:\s*\n\s+needs: \[openrouter_free, resolve_advisory_slots\]\s*\n\s+if: always\(\)/);assert.match(sequence,/EXPECTED_MATRIX/);assert.match(sequence,/structured slot artifacts/i);});
test('governance validation isolates pull_request and pull_request_review concurrency groups',()=>{assert.match(governance,/repository-governance-\$\{\{ github\.ref \}\}-\$\{\{ github\.event_name \}\}/);});
test('review-readiness distinguishes pending checks from completed failures',()=>{
  assert.match(governance,/pending=0\s*\n\s*failed=0/);
  assert.match(governance,/status=missing conclusion=pending/);
  assert.match(governance,/if \[ \"\$status\" != \"completed\" \]/);
  assert.match(governance,/REVIEW_READINESS=WAITING_FOR_REQUIRED_CHECKS/);
  assert.match(governance,/if \[ \"\$failed\" -gt 0 \]/);
});
test('automatic fan-out uses the canonical two-second stagger',()=>{assert.deepEqual(slots.map(s=>s.start_delay_seconds),[0,2,4,6,8]);assert.equal(manifest.advisory_review.automatic.max_spread_seconds,8);assert.match(sequence,/Resolved canonical advisory slot matrix/);assert.match(runner,/START_DELAY_SECONDS/);});
test('runner hard-locks route and uses structured advisory output',()=>{assert.match(runner,/MODEL:\s*openrouter\/free/);assert.doesNotMatch(runner,/^\s+model:\s*$/m);assert.doesNotMatch(runner,/approve:/i);assert.match(runner,/response_format/);assert.match(runner,/'type': 'json_schema'/);assert.match(runner,/teamai_advisory_review/);assert.match(runner,/failure_path\.exists\(\)/);assert.match(runner,/actions\/upload-artifact@v4/);assert.doesNotMatch(runner,/automatic_outcome_marker/);});
test('terminal artifacts preserve provider response and usage diagnostics',()=>{assert.match(runner,/'response_shape': runtime\.get\('response_shape'\)/);assert.match(runner,/'usage_summary': runtime\.get\('usage_summary'\)/);assert.match(runner,/review-manifest\.json/);assert.match(runner,/max_tokens\': 4000/);});
test('provider capability controls remain enforced',()=>{assert.match(runner,/require_parameters/);assert.match(runner,/response-healing/);assert.match(runner,/stream.*False/);});
test('automatic sequence evidence publisher is authenticated',()=>{assert.match(sequence,/Build and publish execution evidence[\s\S]{0,500}GH_TOKEN: \$\{\{ github\.token \}\}/);assert.match(sequence,/gh api --method POST/);});
test('validation workflows avoid duplicate PR branch pushes',()=>{const full=fs.readFileSync(path.join(root,'.github/workflows/full-system-verification.yml'),'utf8');const browser=fs.readFileSync(path.join(root,'.github/workflows/playwright.yml'),'utf8');assert.match(full,/push:\n\s+branches: \[main\]/);assert.match(browser,/push:\n\s+branches: \[main\]/);assert.doesNotMatch(full,/governance\/repository-foundation/);assert.doesNotMatch(browser,/governance\/repository-foundation/);});
test('manual advisory routing is bound to the target PR exact head',()=>{assert.match(manual,/Read target PR head/);assert.match(manual,/ref: \$\{\{ steps\.target\.outputs\.head_sha \}\}/);assert.match(manual,/head_sha: \$\{\{ steps\.target\.outputs\.head_sha \}\}/);assert.match(manual,/expected_head: \$\{\{ needs\.resolve_manual_slot\.outputs\.head_sha \}\}/);assert.doesNotMatch(manual,/github\.event\.repository\.default_branch/);});
test('canonical alias literals remain isolated to the manifest',()=>{for(const alias of aliases){const escaped=escapeRegExp(alias);assert.doesNotMatch(controlPlaneValidator,new RegExp(escaped));assert.doesNotMatch(policy,new RegExp(escaped));assert.doesNotMatch(wiring,new RegExp(escaped));assert.doesNotMatch(skill,new RegExp(escaped));assert.doesNotMatch(session,new RegExp(escaped));}});
test('manual advisory routing enforces the canonical five-slot registry shape',()=>{assert.match(manual,/len\(slots\) != 5/);assert.match(manual,/seen_slots=set\(\)/);assert.match(manual,/seen_aliases=set\(\)/);assert.match(manual,/\[1,2,3,4,5\]/);assert.match(manual,/\[0,2,4,6,8\]/);assert.match(manual,/not alias/);});
test('runner accepts fully bolded Owning/Governing Issue fields',()=>{const issueLine=/^\s*(?:[-*]\s*)?(?:\*\*)?\s*(?:Owning|Governing)\s+Issue:\s*(?:\*\*)?#(\d+)/im;assert.equal('**Owning Issue: #394**'.match(issueLine)?.[1],'394');assert.equal('- **Governing Issue: #393**'.match(issueLine)?.[1],'393');assert.equal('Owning Issue: **#394**'.match(issueLine)?.[1],'394');assert.match(controlPlaneValidator,/\(\?:\*\*\)\?\\s\*\(\?:Owning\|Governing\)\\s\+Issue/);});
test('manual routing and documentation consume the canonical registry',()=>{assert.match(manual,/resolve_manual_slot/);assert.match(manual,/fromJSON\(needs\.resolve_manual_slot\.outputs\.matrix\)/);assert.match(manual,/secrets\[matrix\.credential_alias\]/);assert.match(wiring,/\.github\/teamai\/authority-manifest\.yml/);assert.match(skill,/\.github\/teamai\/authority-manifest\.yml/);for(const alias of aliases){const escaped=escapeRegExp(alias);assert.doesNotMatch(policy,new RegExp(escaped));assert.doesNotMatch(wiring,new RegExp(escaped));assert.doesNotMatch(skill,new RegExp(escaped));assert.doesNotMatch(session,new RegExp(escaped));}});
for(const text of [sequence,runner,manual,policy,wiring,skill,next]) for(const token of ['1→2→2','150-second','one shared OpenRouter API key','comment-driven orchestration state','skills/governance/nemotron-copilot-review']) { const escaped = token.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); assert.doesNotMatch(text,new RegExp(escaped,'i')); }
test('retired files are archived, not active',()=>{assert.equal(fs.existsSync(path.join(root,'docs/TEAMAI_029_CURRENT_STATE_MAP.md')),false);assert.equal(fs.existsSync(path.join(root,'.github/workflows/nemotron-copilot-review.yml')),false);assert.equal(fs.existsSync(path.join(root,'skills/governance/nemotron-copilot-review/SKILL.md')),false);assert.equal(fs.existsSync(path.join(root,'docs/archive/TEAMAI_029_CURRENT_STATE_MAP_legacy_2026-09-19.md')),true);});
test('session snapshot and current slice are explicit',()=>{assert.match(session,/## SESSION SNAPSHOT/);assert.match(session,/main baseline:\s*`?867944b03776f47fb01bd2cddf90ed4c70ab3b68/);const currentSlice=next.match(/^## Current Slice\s*\n([^\n]+)/m)?.[1]?.trim();assert.ok(currentSlice);assert.match(session,new RegExp('current slice:\\s*'+escapeRegExp(currentSlice)));});