import assert from 'node:assert/strict';
import test from 'node:test';
import { createMachineScene, createMachineTransition, deriveMachineSubject, expandMachinePart, resolveMachineCamera } from '../frontend/spatial/machine-hero-scene.js';

const source={id:'s0',semanticId:'SEAT_CONNECTION',center:{x:-1,y:.5,z:0},dimensions:{x:2,y:1,z:1.4},port:{x:0,y:.5,z:0}};
const target={id:'s1',semanticId:'SEAT_BEHAVIOR',center:{x:1,y:.5,z:0},dimensions:{x:1.6,y:1,z:1.2},port:{x:1,y:.5,z:0}};
const reverseSource={id:'r0',semanticId:'SEAT_BEHAVIOR',center:{x:1.4,y:.5,z:.8},dimensions:{x:1.6,y:1,z:1.2},port:{x:.9,y:.5,z:.8}};
const reverseTarget={id:'r1',semanticId:'SEAT_CONNECTION',center:{x:3.2,y:.5,z:1.1},dimensions:{x:2,y:1,z:1.4},port:{x:3,y:.5,z:1.1}};

test('canonical transition contains machine contract',()=>{const t=createMachineTransition({seatIndex:0,source,target,expansion:{sourceAmount:.25,targetAmount:.75},wiring:{id:'wire-1'}});assert.equal(t.sourceDivisionId,'SEAT_CONNECTION');assert.equal(t.targetDivisionId,'SEAT_BEHAVIOR');assert.ok(t.sourceGeometry.dimensions.x>source.dimensions.x);assert.ok(t.targetGeometry.dimensions.x>target.dimensions.x);assert.ok(t.sourceGeometry.center.x<source.center.x);assert.ok(t.targetGeometry.center.x>target.center.x);assert.deepEqual(t.wiring.sourcePort,t.sourcePort);assert.deepEqual(t.wiring.targetPort,t.targetPort);assert.equal(t.wiring.id,'wire-1');assert.equal(t.wiring.route.length,3);assert.ok(t.subject);});
test('division expansion is a geometry operation, not just a scalar state',()=>{const collapsed=expandMachinePart(target,0);const expanded=expandMachinePart(target,1,{direction:1});assert.deepEqual(collapsed.dimensions,target.dimensions);assert.ok(expanded.dimensions.x>target.dimensions.x);assert.ok(expanded.dimensions.y>target.dimensions.y);assert.ok(expanded.dimensions.z>target.dimensions.z);assert.ok(expanded.center.x>target.center.x);assert.notDeepEqual(expanded.port,target.port);assert.deepEqual(target.dimensions,{x:1.6,y:1,z:1.2});});
test('subject follows geometry mutation',()=>{const a=deriveMachineSubject([source,target]);const b=deriveMachineSubject([source,{...target,center:{x:2.5,y:.5,z:.75}}]);assert.notDeepEqual(a.center,b.center);assert.ok(b.max.x>a.max.x);assert.ok(b.max.z>a.max.z);});
test('wiring follows moved semantic target port',()=>{const movedTarget={...target,port:{x:2.75,y:.5,z:1.2}};const t=createMachineTransition({source,target:movedTarget,wiring:{id:'wire-2'}});assert.deepEqual(t.wiring.sourcePort,t.sourcePort);assert.deepEqual(t.wiring.targetPort,t.targetPort);assert.deepEqual(t.wiring.route[0],t.sourcePort);assert.deepEqual(t.wiring.route[2],t.targetPort);});
test('missing semantic port fails closed for wiring',()=>{const t=createMachineTransition({source,target:{...target,port:null}});assert.equal(t.wiring,null);});
test('same camera algorithm works for a different semantic pair',()=>{const forward=createMachineTransition({source,target});const alternate=createMachineTransition({seatIndex:0,source:reverseSource,target:reverseTarget});const a=resolveMachineCamera({cameraId:'SEAT_CLOSE',subject:forward.subject});const b=resolveMachineCamera({cameraId:'SEAT_CLOSE',subject:alternate.subject});assert.equal(a.cameraId,b.cameraId);assert.notDeepEqual(a.target,b.target);});
test('camera identity stays named while target follows subject',()=>{const a=createMachineTransition({source,target});const b=createMachineTransition({source,target:{...target,center:{x:3.25,y:.5,z:1.5}}});const c=resolveMachineCamera({cameraId:'SEAT_CLOSE',subject:a.subject});const d=resolveMachineCamera({cameraId:c.cameraId,subject:b.subject});assert.equal(c.cameraId,'SEAT_CLOSE');assert.equal(d.cameraId,'SEAT_CLOSE');assert.notDeepEqual(d.target,c.target);});
test('scene graph normalizes parts and transitions under one immutable machine object',()=>{const scene=createMachineScene({seatIndex:0,parts:[source,target],transitions:[{source,target}]});assert.equal(scene.parts.length,2);assert.equal(scene.transitions.length,1);assert.ok(scene.subject);assert.equal(scene.transitions[0].sourceDivisionId,'SEAT_CONNECTION');assert.equal(scene.transitions[0].targetDivisionId,'SEAT_BEHAVIOR');assert.equal(Object.isFrozen(scene),true);assert.equal(Object.isFrozen(scene.parts),true);assert.equal(Object.isFrozen(scene.transitions),true);});
test('invalid transition fails closed',()=>assert.throws(()=>createMachineTransition({source,target:{...target,semanticId:null}})));
