import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

const rendererScript = readFileSync(new URL('../scripts/apply-031-seat1-adjacent-wiring-render.mjs', import.meta.url), 'utf8');

test('Seat-1 adjacent wiring renderer is generated by the canonical semantic wiring patcher', () => {
  assert.match(rendererScript, /function drawSeat1AdjacentDivisionWiring\(/);
  assert.match(rendererScript, /buildAdjacentDivisionWiring\(/);
  assert.match(rendererScript, /adjacentDivisionWiringPoint\(/);
  assert.match(rendererScript, /connectionBranchAmount/);
  assert.match(rendererScript, /behaviorBranchAmount/);
});

test('Seat-1 adjacent wiring follows sequential expansion phases', () => {
  assert.match(rendererScript, /const activeAmount = targetAmount > 0 \? targetAmount : sourceAmount/);
  assert.match(rendererScript, /phase: targetAmount > 0 \? 'TARGET_OPENING_OR_ACTIVE' : 'SOURCE_OPENING_OR_ACTIVE'/);
  assert.match(rendererScript, /hierarchyRuntime\.seat1AdjacentWiring = null/);
});
