export type WorkflowState = 'DISCUSSING'|'READY_TO_SUMMARIZE'|'SUMMARIZING'|'PENDING_APPROVAL'|'APPROVED'|'EXECUTING'|'REVIEWING'|'COMPLETED'|'FAILED'|'CANCELLED';
export type WorkflowEvent = 'DISCUSSION_COMPLETE'|'START_SUMMARY'|'SUMMARY_READY'|'APPROVE'|'REJECT'|'START_EXECUTION'|'EXECUTION_DONE'|'REVIEW_DONE'|'FAIL'|'CANCEL';
const transitions: Record<WorkflowState, Partial<Record<WorkflowEvent,WorkflowState>>> = {
 DISCUSSING:{DISCUSSION_COMPLETE:'READY_TO_SUMMARIZE',CANCEL:'CANCELLED',FAIL:'FAILED'},
 READY_TO_SUMMARIZE:{START_SUMMARY:'SUMMARIZING',CANCEL:'CANCELLED'},
 SUMMARIZING:{SUMMARY_READY:'PENDING_APPROVAL',FAIL:'FAILED',CANCEL:'CANCELLED'},
 PENDING_APPROVAL:{APPROVE:'APPROVED',REJECT:'DISCUSSING',CANCEL:'CANCELLED'},
 APPROVED:{START_EXECUTION:'EXECUTING',CANCEL:'CANCELLED'},
 EXECUTING:{EXECUTION_DONE:'REVIEWING',FAIL:'FAILED',CANCEL:'CANCELLED'},
 REVIEWING:{REVIEW_DONE:'COMPLETED',FAIL:'FAILED',CANCEL:'CANCELLED'},
 COMPLETED:{},FAILED:{},CANCELLED:{}
};
export function transition(state:WorkflowState,event:WorkflowEvent):WorkflowState{const next=transitions[state][event];if(!next)throw new Error(`invalid transition ${state} -> ${event}`);return next;}
